#!/usr/bin/env python3
"""TRT traceability build.

Loads traceability/claims/*.yaml, validates them, checks the dependency graph is
acyclic (the circularity discipline), verifies Lean artifact files exist, and emits
generated reports: claims.json, coverage-report.md, dependency-graph.{mmd,json},
risk-report.md.

Usage:  python3 traceability/scripts/build.py
Exit code is nonzero if validation fails (suitable for CI).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CLAIMS_DIR = ROOT / "traceability" / "claims"
GEN_DIR = ROOT / "traceability" / "generated"
FORMAL_DIR = ROOT / "formalization"

ID_PREFIXES = {"ONT", "LOG", "ACT", "QM", "PHY", "INT", "PRD", "OPN", "EXT"}
REQUIRED = ["id", "name", "statement", "tier", "role", "proof_status", "epistemic_status"]
PROOF_ORDER = ["verified", "imported", "axiomatized", "prose_only", "open"]
EPI_ORDER = ["established", "argued", "conjectured", "open"]
TIER_NAME = {0: "strategy", 1: "hypothesis (hard core)", 2: "theory (belt)", 3: "prediction"}


def cell(s) -> str:
    """Escape a value for use inside a markdown table cell."""
    return str(s).replace("|", "\\|").replace("\n", " ").strip()


def load_claims() -> dict:
    claims = {}
    for p in sorted(CLAIMS_DIR.glob("*.yaml")):
        with p.open() as f:
            c = yaml.safe_load(f)
        c["_file"] = p.name
        claims[c["id"]] = c
    return claims


def validate(claims: dict) -> list[str]:
    errs = []
    for cid, c in claims.items():
        for field in REQUIRED:
            if field not in c or c[field] in (None, ""):
                errs.append(f"{cid}: missing required field '{field}'")
        if cid.split("-")[0] not in ID_PREFIXES:
            errs.append(f"{cid}: unknown id prefix")
        # predictions must state a falsification condition
        if c.get("role") == "prediction" and not c.get("falsifies"):
            errs.append(f"{cid}: role=prediction but no 'falsifies' (Popperian) field")
        # dangling dependency refs
        for dep in c.get("depends_on") or []:
            ref = dep.get("claim_id")
            if ref not in claims:
                errs.append(f"{cid}: depends_on dangling ref '{ref}'")
        # Lean artifact files must exist
        for art in (c.get("formal_artifacts") or {}).get("lean", []):
            if not (FORMAL_DIR / art["file"]).exists():
                errs.append(f"{cid}: lean artifact file missing: {art['file']}")
    return errs


def find_cycles(claims: dict) -> list[list[str]]:
    """DFS cycle detection over depends_on edges (must be acyclic)."""
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {cid: WHITE for cid in claims}
    cycles, stack = [], []

    def dfs(u):
        color[u] = GRAY
        stack.append(u)
        for dep in claims[u].get("depends_on") or []:
            v = dep.get("claim_id")
            if v not in claims:
                continue
            if color[v] == GRAY:
                cycles.append(stack[stack.index(v):] + [v])
            elif color[v] == WHITE:
                dfs(v)
        stack.pop()
        color[u] = BLACK

    for cid in claims:
        if color[cid] == WHITE:
            dfs(cid)
    return cycles


def counts(claims: dict, key: str, order: list[str] | None = None) -> list[tuple[str, int]]:
    tally: dict = {}
    for c in claims.values():
        tally[c.get(key)] = tally.get(c.get(key), 0) + 1
    items = sorted(tally.items(), key=lambda kv: (order.index(kv[0]) if order and kv[0] in order else 99, str(kv[0])))
    return items


def write_claims_json(claims: dict):
    out = {cid: {k: v for k, v in c.items() if k != "_file"} for cid, c in claims.items()}
    (GEN_DIR / "claims.json").write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")


def write_coverage(claims: dict):
    lines = ["# Coverage Report", "", "*Generated by `traceability/scripts/build.py` — do not edit by hand.*", "",
             f"**Total claims: {len(claims)}**", ""]
    for title, key, order in [("By tier", "tier", None), ("By role", "role", None),
                              ("By proof status", "proof_status", PROOF_ORDER),
                              ("By epistemic status", "epistemic_status", EPI_ORDER)]:
        lines.append(f"## {title}")
        lines.append("")
        for k, n in counts(claims, key):
            label = f"{k} — {TIER_NAME[k]}" if key == "tier" else str(k)
            lines.append(f"- **{label}**: {n}")
        lines.append("")
    # full table
    lines += ["## All claims", "", "| ID | Tier | Role | Proof | Epistemic | Name |",
              "|---|---|---|---|---|---|"]
    for cid in sorted(claims):
        c = claims[cid]
        lines.append(f"| {cid} | {c['tier']} | {c['role']} | {c['proof_status']} | {c['epistemic_status']} | {cell(c['name'])} |")
    lines.append("")
    (GEN_DIR / "coverage-report.md").write_text("\n".join(lines))


def write_depgraph(claims: dict):
    edges = []
    for cid, c in claims.items():
        for dep in c.get("depends_on") or []:
            edges.append({"from": cid, "to": dep.get("claim_id"), "type": dep.get("dependency_type")})
    (GEN_DIR / "dependency-graph.json").write_text(json.dumps({"nodes": sorted(claims), "edges": edges}, indent=2) + "\n")
    mmd = ["graph TD"]
    for cid in sorted(claims):
        c = claims[cid]
        mmd.append(f'  {cid}["{cid}<br/>{c["role"]}/{c["proof_status"]}"]')
    for e in edges:
        mmd.append(f'  {e["from"]} --> {e["to"]}')
    (GEN_DIR / "dependency-graph.mmd").write_text("\n".join(mmd) + "\n")


def write_risk(claims: dict):
    lines = ["# Risk Report", "", "*Generated — failure conditions and Popperian refutation conditions.*", "",
             "## Predictions (`falsifies`)", "", "| ID | Name | Refuted if |", "|---|---|---|"]
    for cid in sorted(c for c in claims if claims[c].get("role") == "prediction"):
        c = claims[cid]
        lines.append(f"| {cid} | {cell(c['name'])} | {cell(c.get('falsifies') or '')} |")
    lines += ["", "## All failure conditions (`risk_if_false`)", "", "| ID | Tier | Risk if false |", "|---|---|---|"]
    for cid in sorted(claims):
        c = claims[cid]
        r = cell(c.get("risk_if_false") or "")
        if r:
            lines.append(f"| {cid} | {c['tier']} | {r} |")
    lines.append("")
    (GEN_DIR / "risk-report.md").write_text("\n".join(lines))


def main() -> int:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    claims = load_claims()
    errs = validate(claims)
    cycles = find_cycles(claims)
    for cyc in cycles:
        errs.append(f"CIRCULARITY: dependency cycle {' -> '.join(cyc)}")

    write_claims_json(claims)
    write_coverage(claims)
    write_depgraph(claims)
    write_risk(claims)

    print(f"loaded {len(claims)} claims; generated 4 reports in {GEN_DIR.relative_to(ROOT)}/")
    verified = sum(1 for c in claims.values() if c["proof_status"] == "verified")
    print(f"  proof_status=verified: {verified}/{len(claims)}")
    print(f"  dependency graph: {'ACYCLIC ✓' if not cycles else 'HAS CYCLES ✗'}")
    if errs:
        print(f"\n{len(errs)} validation error(s):", file=sys.stderr)
        for e in errs:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print("validation: OK ✓")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
